name: Build OpenKore (Windows)

on:
  push:
    branches:
      - main # Ou a branch que você deseja usar

jobs:
  build:
    runs-on: windows-latest # Usa uma máquina virtual Windows mais recente

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.36'

      - name: Install dependencies
        run: |
          cpan install Module::Build
          cpan install Win32::API
          # Instale outras dependências do Openkore, se houver

      - name: Build OpenKore
        run: |
          perl Makefile.PL
          .\build.bat
          # Ou os comandos necessários para compilar o OpenKore

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: openkore-windows
          path: |
            openkore.exe
            # Outros arquivos que você queira disponibilizar como artefatos
