name: Build OpenKore (Windows)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout OpenKore code
        uses: actions/checkout@v3
        with:
          repository: OpenKore/openkore
          ref: master
          submodules: true

      - name: Install Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.36'

      - name: Install dependencies
        run: |
          cpan install Module::Build
          cpan install Win32::API

      - name: Build OpenKore
        run: |
          cd src # Mude 'src' para o subdiretório correto onde Build.PL está localizado, se diferente.
          perl Build.PL
          .\Build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: openkore-windows
          path: |
            *.exe
